//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Price()
        {
            this.Boats = new HashSet<Boat>();
        }
    
        public int PriceID { get; set; }
        public decimal BasicFee { get; set; }
        public decimal HourFee { get; set; }
        public Nullable<decimal> BasicPriceSmallBoatAlgorithm { get; set; }
        public Nullable<decimal> BasicPriceBigBoatAlgorithm { get; set; }
        public Nullable<decimal> HourPriceSmallBoatAlgorithm { get; set; }
        public Nullable<decimal> HourPriceBigBoatAlgorithm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boat> Boats { get; set; }
    }
}
